version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest"
    ports:
      - 27017:27017
  db-test:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27018:27017
