name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        test:
          [
            nestjs-api-mongoose,
            nestjs-graphql-mercurius-code-first,
            nestjs-graphql-mercurius-schema-first,
          ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
      with: 
        version: 7
        run_install: true
    - run: npx nx test ${{ matrix.test }}
