name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        test:
          [
            nestjs-api-mongoose,
            nestjs-api-sequelize,
            nestjs-graphql-mercurius-code-first,
            nestjs-graphql-mercurius-schema-first,
          ]
    steps:
      - uses: actions/checkout@v3
        name: Use Node.js ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        name: Install pnpm
      - run: pnpm install --frozen-lockfile
      - run: npx nx test ${{ matrix.test }}
